apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-datawaybr-scheduler
  namespace: orquestrator
subjects:
  - kind: ServiceAccount
    name: airflow-datawaybr-scheduler
    namespace: orquestrator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io