#
# Spark Application Manifest
# Exemplo retirado do git kubeflow-spark-operator
# Executa um script de exemplo em Scala que calcula o número PI em loop
#
# Expoe na sessao monitoring do YAML as metricas e os arquivos
# necessarios para entregar as metricas do Spark
#

apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: operator
spec:
  type: Scala
  mode: cluster
  image: <repo-docker-hub/imagem:tag>
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples.jar
  arguments:
  - "100"
  sparkVersion: 3.5.3
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: 512m
    labels:
      version: 3.5.3
    serviceAccount: spark-operator-datawaybr-spark
  executor:
    cores: 1
    instances: 1
    memory: 512m
    labels:
      version: 3.5.3
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: /prometheus/jmx_prometheus_javaagent-0.11.0.jar
      port: 8090
      portName: prometheus