apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spark-pod-pi-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      sparkoperator.k8s.io/app-name: spark-pi
      spark-role: driver
      sparkoperator.k8s.io/launched-by-spark-operator: "true"
  namespaceSelector:
    matchNames:
      - operator  # Nome do namespace onde o Spark está rodando
  podMetricsEndpoints:
  - path: /metrics
    port: prometheus
    interval: 15s
    scrapeTimeout: 10s