apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-dex-server
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s