apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:seu-git/nome-repo.git'
    path: helm-charts/minio-tenant
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
      name: 'in-cluster'
      namespace: storage
      server: ''
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
